name: Deploy Supabase Edge Functions

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link project
        run: |
          supabase link --project-ref "dmzmsgolisgcvbfaekby" --debug
        env:
          SUPABASE_ACCESS_TOKEN: "sbp_7198c1b825d0a567e720e20715add64f6fc5385a"

      - name: Deploy Edge Functions
        run: |
          supabase functions deploy --project-ref "dmzmsgolisgcvbfaekby"
        env:
          SUPABASE_ACCESS_TOKEN: "sbp_7198c1b825d0a567e720e20715add64f6fc5385a"
